name: Run tests and publish report
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run the Maven verify phase
        run: mvn clean test -Dtest=AppTest

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Allure Command Line Tool
        id: install-allure-commandline
        run: |
          npm install -g allure-commandline --save-dev  

      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: ramachandranr2007/allure-report-action@master
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_report: allure-report
          allure_results: target/allure-results

      - name: Generate Static Report
        id: generate-static-report
        run: |
          allure generate --clean --single-file allure-report -o new-allure-report 

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history

      - name: Generate artifact name
        id: generate-name
        run: |
          mkdir artifacts
          zip -r artifacts/report.zip new-allure-report/

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: artifacts/report.zip
